name: CI

on:
  push:
    branches: [main, "**"]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - run: npm ci

      - run: npm test

      - run: npm run lint

      - name: Build
        run: npm run build

  docssite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: docssite/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: docssite

      - name: Build
        run: npm run build
        working-directory: docssite
